### ISSUE TITLE
Cards missing in observer mode

### ISSUE THREAD

**Issue by CanKattwinkel** [w11k/calendar-for-trello#101]
from https://github.com/w11k/calendar-for-trello/pull/100

@weavercc:
 > I'm not quite sure if I'm entering this in the right manner, but my organization uses Calendar for Trello and we can't seem to get any of the boards to display across calendars after multiple logins and trying different browsers. Is there a current glitch that needs to be resolved, or are we missing something?

**Comment by CanKattwinkel** [comment]
@weavercc:

could you answer me the following questions:

1. since when are you experiencing this issue?
1. did it work before?
1. What browser are you using?
1. have you tried to use the loading button in order to trigger a manual API refresh?  (image) 
1. are there any errors notifications shown in the bottom right corner? 

Thanks for reporting the issue!

![image](https://cloud.githubusercontent.com/assets/11500619/21615255/05a5cd2c-d1dd-11e6-8176-bfa1565b809f.png)

**Comment by weavercc** [comment]
1.       I’ve been experience this issue on and off for about three months.

2.       It has worked before, but not consistently so, and not for many people.

3.       I’ve tested it in Chrome and IE.

4.       I have tried loading a manual refresh several times.

5.       There appear to be no error notifications in the bottom right corner.

Please let me know if you have any additional questions!

Thanks very much,
Camille

Camille Weaver
Assistant Director of Advancement and Alumni Communications
University of Virginia Darden School of Business
+1-434-243-9224

**Comment by CanKattwinkel** [comment]
@weavercc we are currently hitting the API limit. This is probably causing your issues. We are currently working on a new version of our calendar that implements a way more efficient loading strategy. 

Therefore you issue should be resolved with the release of the new version. You can [try the new version here](https://w11k.github.io/calendar-for-trello/).

**Comment by weavercc** [comment]
Hi there,

It looks like the link is no longer working. Do you have an alternate you can recommend that will be available more permanently?

Thanks very much,
Camille

Camille Weaver
Assistant Director of Advancement and Alumni Communications
University of Virginia Darden School of Business
+1-434-243-9224

**Comment by CanKattwinkel** [comment]
Hello @weavercc,

we've already released the beta as the official version. You can find it at [calendar-for-trello.com](https://calendar-for-trello.com). 

Since you experienced issues before, please confirm back: Does the new version work for you?

**Comment by weavercc** [comment]
Yes, it looks like it’s currently working for me. Thank you very much!

Camille

Camille Weaver
Assistant Director of Advancement and Alumni Communications
University of Virginia Darden School of Business
+1-434-243-9224
