### ISSUE TITLE
Sync Issues with V2 of Hosted Calendar

### ISSUE THREAD

**Issue by studioy** [w11k/calendar-for-trello#109]
Hi there,

My team is using v2 of the hosted calendar (testing) and we have just run into sync issues.

Until now, things have been syncing almost immediately.  However, nearly 20 minutes ago some cards were marked as done, and this change is not updating on the calendar.

Also, some new cards are not showing up at all.

One card that was marked done is now just appearing as empty.

I will attach an image that shows you how things look.
![cal-v2-issues-1](https://cloud.githubusercontent.com/assets/11352027/21827220/f36262e0-d747-11e6-93c3-9bc49dc5d6e1.jpg)

**Comment by CanKattwinkel** [comment]
This issue and #110 are probably connected to the recently released loading of list information from the API. This causes the calendar to throw an error at 13th + stop of rendering. I'll look into it.

**Comment by CanKattwinkel** [comment]
Please try if the issue is already resolved. If not, please send me a screenshot of your developers console [CTRL]+ [SHIFT] + [J] for Chrome. You should renew your data by logging out before.

Thank you for submitting the error!

**Comment by studioy** [comment]
It looks like this is now resolved, thank you for your quick response!
