### ISSUE TITLE
Show card members

### ISSUE THREAD

**Issue by happy4upa** [w11k/calendar-for-trello#117]
It would be greate to see who is responsible for a card.
And to have a filter by people. 
Thanks.

**Comment by jblankenhorn** [comment]
+1 for the filter

**Comment by CanKattwinkel** [comment]
@happy4upa 
The proposed filter replaces the "show cards of all members/show my cards" option. Will be released within this week. Needs further investigation on how to pull the member with as few as possible API requests.

Showing the members on the card might be implemented in the feature as option - maybe as an info panel, maybe above the due time. I don't want to increase the cards size too much!

**Comment by happy4upa** [comment]
Thanks. At the moment I have a workaround - adding initials of the responsible people in the beginning of a card title.

**Comment by CanKattwinkel** [comment]
ToDo: handle users with no avatar
