### ISSUE TITLE
Wrong Days in Month Headers, Don't Match Actual Dates

### ISSUE THREAD

**Issue by lhardie** [w11k/calendar-for-trello#123]
In version 2.0 on the hosted calendar, the days of the week are in German, and they appear to go from Monday to Sunday.

However, this makes the dates incorrect.  The days of the week should go from Sunday to Saturday, and then the dates would be correct.

For example, right now that calendar says that the 1st of January was a Monday, but it was actually a Sunday.

**Comment by CanKattwinkel** [comment]
Thansk @lhardie for submitting the issue!

Actually this got fixed earlier today. We'll ship a new version shortly. See https://github.com/w11k/calendar-for-trello/issues/113 for more information. 

**FYI:** the internationalisation is still in progress but you can already switch to English dates at the settings page!
