### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by FatGuyLaughing** [w11k/calendar-for-trello#133]
I've checked out the master branch on my local machine and then ran the following command `npm install`. Then received the following warnings.

> npm WARN ng2-redux@5.1.2 requires a peer of @angular/core@^2.4.0 but none was installed.
> npm WARN ng2-dnd@2.2.2 requires a peer of @angular/core@^2.4.4 but none was installed.
> npm WARN @angular/flex-layout@2.0.0-beta.4 requires a peer of rxjs@^5.0.1 but none was installed.

I'm not sure how to resolve this. The first two lines require different versions of Angular. Any help would be greatly appreciated. I am sorry if I missed something obvious.

**Comment by CanKattwinkel** [comment]
Hello @FatGuyLaughing,

the warning shoulnd't affect the `npm install` command at all. What happens if you just run `npm run start` afterwards?

**Comment by FatGuyLaughing** [comment]
.... Well I feel dumb ....
> calendar-for-trello@2.0.0-beta.10 start /Users/fatguylaughing/work/calendar-for-trello
> npm run hmr
> 
> 
> calendar-for-trello@2.0.0-beta.10 hmr /Users/fatguylaughing/work/calendar-for-trello
> ng serve --hmr -e=hmr
> 
> NOTICE Hot Module Replacement (HMR) is enabled for the dev server.
>   The project will still live reload when HMR is enabled,
>   but to take advantage of HMR additional application code is required
>   (not included in an angular-cli project by default).
>   See https://webpack.github.io/docs/hot-module-replacement.html
>   for information on working with HMR for Webpack.
> ** NG Live Development Server is running on http://localhost:4200. **
> Hash: 871ccfddafc27f377d5d
> Time: 9690ms
> chunk    {0} main.bundle.js, main.bundle.map (main) 279 kB {2} [initial] [rendered]
> chunk    {1} styles.bundle.js, styles.bundle.map (styles) 33.5 kB {3} [initial] [rendered]
> chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 5.49 MB [initial] [rendered]
> chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
> webpack: bundle is now VALID.

**Comment by CanKattwinkel** [comment]
Perfect, if everything is working you may close this issue. You may want to replace the API key with a personal one before using the calendar on you own host.

Since we are currently in beta key is not in a config file you can change it in the following files: https://github.com/w11k/calendar-for-trello/search?utf8=%E2%9C%93&q=41485cd87d154168dd6db06cdd3ffd69

Get one here: https://trello.com/app-key

**Comment by FatGuyLaughing** [comment]
Thank you the speedy responses and help. Also thanks for the product!
