### ISSUE TITLE
Time that Cards are Due

### ISSUE THREAD

**Issue by glengny** [w11k/calendar-for-trello#135]
Maybe the answer to this one is staring me right in the face, but...

When I create a new card from the calendar it asks me for a due date (and time). If I pick 9:00 a.m., it creates a card that is due at 4:00 a.m.

If I go into the actual Trello software and correct it, the correct time shows up on the calendar.

Is there a simple time zone feature that I'm missing?

Thanks

**Comment by CanKattwinkel** [comment]
Hello @glengny - the calendar is currently in beta. We will fix this issue when we complete the internationalization.  https://github.com/w11k/calendar-for-trello/issues/84

Currently we are blocked due to a bug in angular cli regarding the scss imports when running ngc.

**Comment by glengny** [comment]
Thanks for the speedy reply! I definitely understood at least 17% of your
note!

The software is great — hang in there!

G



From:  Can Kattwinkel <notifications@github.com>
Reply-To:  w11k/calendar-for-trello
<reply+01844a81893355fe6972be7e22b27eef2ea66dfbb76b926392cf0000000114a7f0f79
2a169ce0c2bb2f5@reply.github.com>
Date:  Tuesday, January 31, 2017 at 1:30 AM
To:  w11k/calendar-for-trello <calendar-for-trello@noreply.github.com>
Cc:  Glen Goldstein <glengny@gmail.com>, Mention
<mention@noreply.github.com>
Subject:  Re: [w11k/calendar-for-trello] Time that Cards are Due (#135)


Currently we are blocked due to a bug in angular cli regarding the scss
imports when running ngc.

**Comment by jblankenhorn** [comment]
@glengny 
- I do not have the problem
- in which timezone are you?
