### ISSUE TITLE
Calendar does not scroll

### ISSUE THREAD

**Issue by RonLonden** [w11k/calendar-for-trello#140]
Not sure why, but in Safari and Chrome on a Mac, the calendar does not scroll to the bottom of the screen. If my week / month is busy (and it always is), I have no way to get to the bottom of the screen. 

Those great buttons at the bottom are inaccessible to me. Giving is scroll capability (or better yet, auto-scroll that follows a drag) would be great.

LOVE the calendar, by the way.

RL

**Comment by jblankenhorn** [comment]
Same here!

**Comment by sensia** [comment]
Same here. When will this be fixed?

**Comment by CanKattwinkel** [comment]
I'll look into it today @sensia

**Comment by sensia** [comment]
Thank you @CanKattwinkel

**Comment by sensia** [comment]
Thanks i't working again!

**Comment by RonLonden** [comment]
Thank you!
