### ISSUE TITLE
Hide Cards from Closed Boards

### ISSUE THREAD

**Issue by russellrosie** [w11k/calendar-for-trello#144]
on the Overdue Card list in the left menu, the list picks up cards from closed boards. it would be great to hide them, or to give the option to hide them. otherwise boards need to be re-opened to administrate the list.

**Comment by CanKattwinkel** [comment]
Hello @niceaddress, thanks for reporting the bug, I'll take care of it. closed boards should be filtered by default.

**Comment by jblankenhorn** [comment]
fixed with #172
