### ISSUE TITLE
Dragging cards to 'archive card' deletes them

### ISSUE THREAD

**Issue by mmiller20** [w11k/calendar-for-trello#146]
Dragging a card into the 'archive card' slot deletes the card on the source board  (using chrome 55.0.2883.105).  I am able to duplicate this from multiple boards and from both the weekly and monthly views within calendar-for-trello.  Thanks - Mike.

**Comment by CanKattwinkel** [comment]
Hello @mmiller20,

thank you for reporting this bug! I'll take care of it.

**Comment by CanKattwinkel** [comment]
Fixed, will be shipped with next release.
