### ISSUE TITLE
Cannot switch between All Members and just my cards

### ISSUE THREAD

**Issue by lhardie** [w11k/calendar-for-trello#150]
I believe I am seeing an error.  I cannot switch between seeing the cards for "All Members" and the cards that are just mine.

I am attaching an image to show you what I see.

In the top right beside the "Add Card" and "Week" buttons, I see an option that looks like a dropdown.  It says "All Member..."

I assume I should be able to click on it and have some options. However, when I click it, I see a white box that says "All Member..." and clicking it does nothing.

See the attached image for what it looks like when I click it.

![cal-for-trello-issue1](https://cloud.githubusercontent.com/assets/5696599/23410071/2f6d5682-fd8b-11e6-82a1-d0b22bfe08b8.JPG)

**Comment by lhardie** [comment]
Just a note, but I would love to do a little digging myself and see if I can figure this out.  I'd be happy to contribute.

**Comment by CanKattwinkel** [comment]
Feel free to contribute at any time! 

It might be that this bug is connected to old data in the localstorage. Have you tried to use the clear data function? 

![image](https://cloud.githubusercontent.com/assets/11500619/23411874/08fd7d30-fdd4-11e6-9c27-2790ea78ea9f.png)

**Comment by lhardie** [comment]
That worked! Thank you for your help!
