### ISSUE TITLE
Some Cards Not Appearing

### ISSUE THREAD

**Issue by alexander-q** [w11k/calendar-for-trello#152]
Hi guys. I have some cards that fail to appear under some circumstances. Often, removing the due-date and re-adding it will fix the problem. In the case of one board, its due cards appeared once I removed the due date from an overdue card.

I suspect it has something to do with the following scenario - I add a card in Trello during a moment of interrupted connectivity. The card is offline in Trello, and syncs at a later date (often only a few seconds later). Is it the cards that experience this delayed sync that I think are not appearing in the calendar until I remove and re-add the date.

It is as if there is not any kind of global check to make sure the data matches between boards and calendar. I use dozens of boards, which may also cause an issue, though the number of cards with due dates is quite small. Can you speak to this issue?

**Comment by jblankenhorn** [comment]
@alexander-q I also use this heavily but never experienced anything like it ... is the problem still there?
