### ISSUE TITLE
Allow archived cards to be included

### ISSUE THREAD

**Issue by brandywalks** [w11k/calendar-for-trello#155]
It would be great to be able to see archived cards as part of the view. My team in particular archives cards so that we don't have to see them after we're done with them but can still query them if needed - we go through a lot of cards. This could be a toggle feature.

**Comment by jblankenhorn** [comment]
@CanKattwinkel i guess we would need another API Call for this.
- they are not included in our normal requests
- they should only be loaded when the toggle is activated

**Comment by jblankenhorn** [comment]
Out of Scope ...
