### ISSUE TITLE
Move "Remove due date", "Toggle card done" and "Archive card" buckets to vertical side bar

### ISSUE THREAD

**Issue by manupaisable** [w11k/calendar-for-trello#158]
If you have a smallish screen (on a 13'' laptop for e.g.) and a reasonable number of cards, it gets hard to move cards to those "buckets" since they are not usually visible (at bottom of page). 

I often have to zoom out to be able to move a card into a bucket, then zoom in again to be able to read the cards :)

Any chance of moving those buckets to a vertical side bar? Or making it an optional setting?

Thanks!

**Comment by Ollisterhase** [comment]
That is a very good suggestion. On our Notebook the Drag & Drop over the Edge to scroll doesn't work, so it would be great if the field could be on the side.

**Comment by jblankenhorn** [comment]
+1

**Comment by jblankenhorn** [comment]
implemented
