### ISSUE TITLE
Once a card is marked done, card minimizes.

### ISSUE THREAD

**Issue by aein** [w11k/calendar-for-trello#159]
When I have a lot of cards due on the same day, it gets very long.
Once a card is marked done, it is auto-shown in a minimized view. 
On click, it can go back to full view to see the list & board.

![image](https://cloud.githubusercontent.com/assets/5262885/25297988/410ef334-26a6-11e7-9fee-92d11f2ec149.png)

**Comment by jblankenhorn** [comment]
nice idea, but should be optionally

**Comment by jblankenhorn** [comment]
implemented @aein
