### ISSUE TITLE
Board Toggle View Feature in Calendar View

### ISSUE THREAD

**Issue by aein** [w11k/calendar-for-trello#160]
First, you have chosen your boards in settings for which are to be shown or not.

Then on calendar view:
- there is a dropdown at the top where all selected Boards are shown
- hide and show Lists at board by clicking List name in the bar

For an easy way to see cards and deadlines for each board you are keeping track of.

**Comment by jblankenhorn** [comment]
@aein I am a bit confused ... what exactly do you propose?

**Comment by jblankenhorn** [comment]
I like it ;)
