### ISSUE TITLE
Removed Due Date but still appeards overdue even when card permanently deleted

### ISSUE THREAD

**Issue by riversidecommunity** [w11k/calendar-for-trello#162]
Hi,

I use the Cards overdue list a lot.

I clicked on an overdue task, then I removed the due date from the card.

I refreshed Calendar for Trello and it remained.
I refreshed the card, it had no due date
I refreshed Calendar for Trello and it remained.
I deleted the card, I refreshed Calendar for Trello and it remained.
I permanently deleted the card. I refreshed Calendar for Trello and it remained.

**Comment by kaihenzler** [comment]
@riversidecommunity I wasn't able to reproduce this issue. Did this happen more than once?
