### ISSUE TITLE
Calendar Refresh does not update current Date

### ISSUE THREAD

**Issue by justvlade** [w11k/calendar-for-trello#166]
When leaving calendar for trello at working computer at night. After returning to work, I have to reload page, for the current date to light up. Else it will show me, that "today" is the previous day.
I expect, that refresh would also check date change.
Not sure if it is a bug or a feature request.

**Comment by fvonberg** [comment]
@CanKattwinkel could you please verify my solution, I am not sure, if the Refresh Button should know about the CalendarType.
