### ISSUE TITLE
Bump dependencies / fix Reselect

### ISSUE THREAD

**Issue by kaihenzler** [w11k/calendar-for-trello#171]
work is in branch: 168-add-multiple-team-members

All dependencies have been bumped to the most recent version in order to resolve issue #168 

Unfortunately the Reselect Module does not seem to work anymore and I had to workaround it by eliminating it when boards have to be selected from the redux store

**Comment by jblankenhorn** [comment]
@CanKattwinkel @kaihenzler current status?

**Comment by CanKattwinkel** [comment]
Oh this is merged. Therefore I'm going to close this issue.
