### ISSUE TITLE
Archived / deleted boards still showing

### ISSUE THREAD

**Issue by mvevle** [w11k/calendar-for-trello#172]
I've archived and deleted a board that I no longer want to see or have record of. The due dates I had assigned to the cards are still showing up on the calendar. The gray cards on the 1st, 15th, and 29th are the ones that should have disappeared. I also have no luck when trying to mark as done or dragging to the "archive card" pad. 
![screen shot 2017-06-14 at 9 27 22 am](https://user-images.githubusercontent.com/29432815/27134552-ecaee908-50e3-11e7-8644-7d02c12fb0c7.png)

**Comment by jblankenhorn** [comment]
@CanKattwinkel do we get Updates from Trello when a board is archived?

**Comment by jblankenhorn** [comment]
@mvevle Fixed!

**Comment by jblankenhorn** [comment]
`ErrorHandler
15:14:02.424 vendor.42accfc73d3ecd895f51.bundle.js:1 this.allBoards$.take is not a function
t.(anonymous function) @ vendor.42accfc73d3ecd895f51.bundle.js:1
n.handleError @ main.cec97e99378b24fed41d.bundle.js:1
next @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.object.i @ vendor.42accfc73d3ecd895f51.bundle.js:1
E9/g.e.__tryOrUnsub @ vendor.42accfc73d3ecd895f51.bundle.js:1
E9/g.e.next @ vendor.42accfc73d3ecd895f51.bundle.js:1
E9/g.e._next @ vendor.42accfc73d3ecd895f51.bundle.js:1
E9/g.e.next @ vendor.42accfc73d3ecd895f51.bundle.js:1
TO51.e.next @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.emit @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invoke @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.run @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
t.runOutsideAngular @ vendor.42accfc73d3ecd895f51.bundle.js:1
onHandleError @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.handleError @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.runTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
t.invokeTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
p @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
d @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
XMLHttpRequest.send (async)
h.scheduleMacroTask.t @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onScheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.scheduleMacroTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
(anonymous) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
o.(anonymous function) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
AP4T.t._trySubscribe @ vendor.42accfc73d3ecd895f51.bundle.js:1
AP4T.t.subscribe @ vendor.42accfc73d3ecd895f51.bundle.js:1
_fetchBoards @ main.cec97e99378b24fed41d.bundle.js:1
pull @ main.cec97e99378b24fed41d.bundle.js:1
n.doRefresh @ main.cec97e99378b24fed41d.bundle.js:1
(anonymous) @ main.cec97e99378b24fed41d.bundle.js:1
T14+.e.__tryOrUnsub @ vendor.42accfc73d3ecd895f51.bundle.js:1
T14+.e.next @ vendor.42accfc73d3ecd895f51.bundle.js:1
T14+.e._next @ vendor.42accfc73d3ecd895f51.bundle.js:1
T14+.e.next @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.dispatch @ vendor.42accfc73d3ecd895f51.bundle.js:1
Io40.e._execute @ vendor.42accfc73d3ecd895f51.bundle.js:1
Io40.e.execute @ vendor.42accfc73d3ecd895f51.bundle.js:1
I2Y9.e.flush @ vendor.42accfc73d3ecd895f51.bundle.js:1
r @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invokeTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onInvokeTask @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invokeTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.runTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
t.invokeTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
i.isUsingGlobalCallback.invoke @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
n.args.(anonymous function) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
setInterval (async)
(anonymous) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onScheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.scheduleMacroTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
(anonymous) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
o.(anonymous function) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
Io40.e.requestAsyncId @ vendor.42accfc73d3ecd895f51.bundle.js:1
Io40.e.schedule @ vendor.42accfc73d3ecd895f51.bundle.js:1
t.schedule @ vendor.42accfc73d3ecd895f51.bundle.js:1
e._subscribe @ vendor.42accfc73d3ecd895f51.bundle.js:1
t._trySubscribe @ vendor.42accfc73d3ecd895f51.bundle.js:1
t.subscribe @ vendor.42accfc73d3ecd895f51.bundle.js:1
n.ngOnInit @ main.cec97e99378b24fed41d.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
ye @ vendor.42accfc73d3ecd895f51.bundle.js:1
Ce @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ main.cec97e99378b24fed41d.bundle.js:1
updateDirectives @ vendor.42accfc73d3ecd895f51.bundle.js:1
me @ vendor.42accfc73d3ecd895f51.bundle.js:1
xe @ vendor.42accfc73d3ecd895f51.bundle.js:1
ve @ vendor.42accfc73d3ecd895f51.bundle.js:1
me @ vendor.42accfc73d3ecd895f51.bundle.js:1
t.detectChanges @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.tick @ vendor.42accfc73d3ecd895f51.bundle.js:1
e._loadComponent @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.bootstrap @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
e._moduleDoBootstrap @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invoke @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onInvoke @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invoke @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.run @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
(anonymous) @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.invokeTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onInvokeTask @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invokeTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.runTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
o @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
Promise resolved (async)
r @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onScheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.scheduleTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.scheduleMicroTask @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
u @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
e.then @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
BkNc.t.appInitializer @ vendor.42accfc73d3ecd895f51.bundle.js:1
t.runInitializers @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
(anonymous) @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invoke @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
onInvoke @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.invoke @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
r.run @ polyfills.2c152db3eb62eb204fcf.bundle.js:1
t.run @ vendor.42accfc73d3ecd895f51.bundle.js:1
e._bootstrapModuleFactoryWithZone @ vendor.42accfc73d3ecd895f51.bundle.js:1
e.bootstrapModuleFactory @ vendor.42accfc73d3ecd895f51.bundle.js:1
vo @ main.cec97e99378b24fed41d.bundle.js:1
cDNt @ main.cec97e99378b24fed41d.bundle.js:1
n @ inline.3e0a239e4a3f88ea478d.bundle.js:1
0 @ main.cec97e99378b24fed41d.bundle.js:1
n @ inline.3e0a239e4a3f88ea478d.bundle.js:1
window.webpackJsonp @ inline.3e0a239e4a3f88ea478d.bundle.js:1
(anonymous) @ main.cec97e99378b24fed41d.bundle.js:1
15:14:02.426 vendor.42accfc73d3ecd895f51.bundle.js:1 TypeError: this.allBoards$.take is not a function
    at n._removeBoards (main.cec97e99378b24fed41d.bundle.js:1)
    at e._next (main.cec97e99378b24fed41d.bundle.js:1)
    at e.E9/g.e.__tryOrUnsub (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at e.E9/g.e.next (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at e.E9/g.e._next (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at e.E9/g.e.next (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at XMLHttpRequest.a (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at XMLHttpRequest.r (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at e.invokeTask (polyfills.2c152db3eb62eb204fcf.bundle.js:1)
    at Object.onInvokeTask (vendor.42accfc73d3ecd895f51.bundle.js:1)
    at e.invokeTask (polyfills.2c152db3eb62eb204fcf.bundle.js:1)
    at r.runTask (polyfills.2c152db3eb62eb204fcf.bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.2c152db3eb62eb204fcf.bundle.js:1)
    at p (polyfills.2c152db3eb62eb204fcf.bundle.js:1)
    at XMLHttpRequest.d (polyfill`

**Comment by jblankenhorn** [comment]
![capturfiles-nov -07-2017_15 15 01](https://user-images.githubusercontent.com/138586/32497919-73e11038-c3ce-11e7-9c8d-0cf8d7d832b7.jpg)

**Comment by jblankenhorn** [comment]
@CanKattwinkel this error only occurs in production

**Comment by CanKattwinkel** [comment]
@jblankenhorn seams like a missing take import for RxJS?

**Comment by jblankenhorn** [comment]
@CanKattwinkel yes, thats what it was 

`import 'rxjs/add/operator/take';`
