### ISSUE TITLE
Moving a card to a different board, causes duplicate in calendar view.

### ISSUE THREAD

**Issue by jordanlui** [w11k/calendar-for-trello#173]
Creating a card under one board and moving to a different board will leave two instances of same card existing in calendar view. One card will exist in each board.
Looking at hyperlink indicates two different URL, but eventually one of them redirects to the single new card URL. So to summarize: Clicking either card in Calendar view directs to the one single card, which was moved to new board.

Things I have tried, and didn't work.
Refreshing view or hitting "trigger refresh" does not fix. 

Things that fix issue:
Interestingly, replicating the problem by creating new different card, assigning due date, and moving it to another board will fix issue with the current card. But then there is a new duplicated card.

Also, creating a different card, assigning due date, and then archiving this card will fix the issue with the other duplicated card (even if I don't move this card to replicate the duplication problem).

**Comment by Ollisterhase** [comment]
It also helps, when you logout and in after that. But then all your settings are gone like giving boards different colours.

**Comment by jblankenhorn** [comment]
fixed
