### ISSUE TITLE
Feature Request - week start 

### ISSUE THREAD

**Issue by skymaster420** [w11k/calendar-for-trello#176]
Ability to set week start day as Monday.
List days as
Mon / Tues / Wed / Thurs / Fri / Sat / Sun

**Comment by Ollisterhase** [comment]
When you set your language to "Deutsch" the week starts at monday.

**Comment by skymaster420** [comment]
Yes this is great however I`m not Deutsch.

**Comment by skymaster420** [comment]
Not sure why this or #157 is marked as closed.
Selecting the date does indeed change the start date but also changes the language. Its now more common internationally for the start of the week to be Monday however the English language sets this as Sunday. Could this be change? or as @aein states an option in the setting would be nice.

**Comment by jblankenhorn** [comment]
@skymaster420 sorry, it was a mistake ;)

**Comment by jblankenhorn** [comment]
Fixed
