### ISSUE TITLE
Can't delete tasks from closed or moved boards

### ISSUE THREAD

**Issue by valerierupp** [w11k/calendar-for-trello#178]
Tasks that are were assigned to a board and later moved show duplicate listings. When I click on the task I'd like to remove it brings me to a screen that says the board no longer exists. (below)

"Card not found.

This card may be on a private board. If someone gave you this link, they may need to invite you to one of their boards or teams."

**Comment by jblankenhorn** [comment]
I believe this is a duplicate of #173
