### ISSUE TITLE
Export to cal

### ISSUE THREAD

**Issue by Alex1982349349** [w11k/calendar-for-trello#179]
Hi! Love the feature.
Ideally Id love to eport it into my outlook and have the flexibility of a sync back, so that if i drag & drop dates or change duration, the deadlines in trello change too! 
Thanks :)

**Comment by jblankenhorn** [comment]
See also https://github.com/w11k/calendar-for-trello/issues/53

**Comment by jblankenhorn** [comment]
Currently a google export is out of scope. Therefore I'm going to close this issue for now.
