### ISSUE TITLE
The card does not appear on the correct date when I update the Due Date

### ISSUE THREAD

**Issue by CommanderKin** [w11k/calendar-for-trello#180]
I had a card with an expired due date. When I updated the due date to a new one that was in the future, the card did not appear on the new date in the Calendar. In order for it too appear there, I had to delete the old due date in the card and create a new one. Not a big issue, but may cause some tasks being forgotten.

**Comment by jblankenhorn** [comment]
@CommanderKin sorry for the late reply, but does this problem still exist on your side?
