### ISSUE TITLE
Google Chrome - Cards Not Shown in Calendar

### ISSUE THREAD

**Issue by mirkomachine** [w11k/calendar-for-trello#183]
I'm experiencing some issues in Google Chrome lately (probably since the last update).

Sometimes trello cards are not shown in the calendar. Then, after cleaning data, everything looks fine for a while. Afterwards the cards disappear again.

I've tested with Opera, where everything looks fine. Also i've deactivated the ad-blocker, and the issue was still there.

P.S. I love Calendar for Trello, and it's one of my most used tools during the day. Thank You for keeping up with the work here. 
Guess I'll definitely have to send you some chocolate for christmas this year!

**Comment by jblankenhorn** [comment]
@mirkomachine Thanks for the warm words, choclate is always very appreciated ;)

Is ist the same cards that do disappear, or is it connected to a reproducable action?

**Comment by mirkomachine** [comment]
So chocolate it shall be then! ;o)

Seems like just cards from a board i recently added are affected. older cards seem working fine.
I'm using the latest Chrome Version 61.0.3163.91

**Comment by CanKattwinkel** [comment]
@mirkomachine 

Can you indicate whether the cards were created on the new board or moved from another board to the new board?

And thanks for reporting the bug!

**Comment by mirkomachine** [comment]
I've created the card on the new board.

also i'te mad a quick test. i don't see the card initially in the trello calendar, bit when i change the date in trello, the card appears again.
during the same process the card was visible in opera.

the member filter is set to all members, i've checked that as well.

**Comment by jblankenhorn** [comment]
@mirkomachine we just released a new version, we hope this is fixed now!

**Comment by mirkomachine** [comment]
people would say - work as designed.

thank you
