### ISSUE TITLE
Calendar-for-trello App

### ISSUE THREAD

**Issue by GraceIm** [w11k/calendar-for-trello#188]
Calendar-for-trello is the only program I've found that does exactly what I need it to do which is combine all boards and tasks onto one calendar! The only thing that would top it is a Calendar-for-trello app!

Is this something that the W11K team will be developing soon? 

Kind regards,
GraceIm

**Comment by jblankenhorn** [comment]
Hello @GraceIm ,

thank you very much ... we would really like to do this, but i fear it will not come in the near future.

Kind regards
Jan
