### ISSUE TITLE
BUG - Unable to select "hidden" status for more than one board.

### ISSUE THREAD

**Issue by rachelpderman** [w11k/calendar-for-trello#190]
When all boards are visible (default) I am able to choose the first one and change to hidden. When I change the second to hidden it overrides the first back to status visible.

**Comment by robthatcher** [comment]
I also see this bug, same behaviour.

**Comment by rachelpderman** [comment]
I still see this bug

**Comment by jblankenhorn** [comment]
@rachelpderman please check again, it was just released 5 seconds ago ;)
