### ISSUE TITLE
Display Problem in Chrome

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/calendar-for-trello#193]
![20180123_073643-capturfiles](https://user-images.githubusercontent.com/138586/35261443-6478feca-0010-11e8-9e09-fd74dd8a5d27.jpg)

@CanKattwinkel can you reproduce this?

**Comment by CanKattwinkel** [comment]
@jblankenhorn no - but might be a Flexbox issue. We could check it out on Friday.
