### ISSUE TITLE
Import ICS Calendar file

### ISSUE THREAD

**Issue by markpape** [w11k/calendar-for-trello#196]
Hi there,

Could you add a calendar import? Similar to https://planyway.com/

**Comment by jblankenhorn** [comment]
Hi @markpape ,

what do you exactly mean?

**Comment by markpape** [comment]
Apologies, i believe i mean a calendar sync, i.e. with outlook. I would love to see my due dates inside of outlook calendar, or meetings from my calendar inside of trello calendar.

**Comment by jblankenhorn** [comment]
@markpape I can really understand the need for this feature, but currently we do not have the time to do this. It would require a Server Application etc ...
