### ISSUE TITLE
Unable to drag and drop cards in Windows 10 PC Chrome

### ISSUE THREAD

**Issue by kngautham** [w11k/calendar-for-trello#198]
I use Chrome and Windows 10. I am not able to do the following
1. Drag and drop cards with Due dates to change due dates
2. Drag and drop cards from the vertical left side without Due dates onto the calendar to set due dates for the cards

Thanks
Gautham

**Comment by kngautham** [comment]
Can someone reply? Is this a problem specific to Chrome?

**Comment by jblankenhorn** [comment]
Hello @kngautham ,

i cannot repdouce this ... 

What you could try is to delete the calendars storage. Use the three dots in the upper right corner and select "Clear Data". Does the problem still occur?

**Comment by kngautham** [comment]
It started working after i cleared data and logged out. Thanks
