### ISSUE TITLE
Please change the third option to Toggle Done Card + Archive instead of just Archiving the card

### ISSUE THREAD

**Issue by kngautham** [w11k/calendar-for-trello#199]
You have three options at the bottom namely - Remove Due date, Toggle Card done and Archive Card.

Can you change the third option to Toggle Done Card + Archive instead of just Archiving the card so that I need to drag my card only once when I need to mark Done and Archive the same card.

Thanks

**Comment by jblankenhorn** [comment]
implemented

**Comment by kngautham** [comment]
Thank you very much for the feature
