### ISSUE TITLE
Sync with calendar clients

### ISSUE THREAD

**Issue by adrm** [w11k/calendar-for-trello#200]
I am using this service because Trello now limits the number of addons to one unless you are a business class customer. The only feature I miss from Trello's calendar addon is the ability to sync with a calendar app on a smartphone. Since I already need to use another addon, I cannot activate the calendar addon. Are you planning to support calendar sync in this project?

Thanks.

**Comment by jblankenhorn** [comment]
Hi @adrm,

we would love this feature, bad sadly this is currently not on our worklist!

Best
