### ISSUE TITLE
Several issues and a request

### ISSUE THREAD

**Issue by welswebmaster** [w11k/calendar-for-trello#201]
Great tool that is needed! Here's a few issues and a feature request: 

ISSUES
1- Days of the week appear in language other than what was chosen in settings intermittently. 
2- Drag and Drop cards to bottom often freezes with no way to recover. Working on a Mac. Tried clear date - no difference. Tried refresh - no difference. Tried CTL-Command-ESC - no difference.
3- Because we have MANY Trello boards, it takes a while for the app to respond when selecting boards. A faster approach might be by default to have NO boards selected upon first use of app. 

FEATURE REQUESTS
1- Would like to see Monthly view displaying M-F and not Sat & Sun in the view. 
2- Could use a list view where each line is a card for a date range. Super useful in annual planning especially if you can filter by board.  (Shows a project annual cycle)

Overall - this app delivers very useful information! Thank you!

**Comment by CanKattwinkel** [comment]
@welswebmaster we just released version 2.1.0 with some performance improvements for powerusers. Could you please verify if issue 2 & 3 are fixed/mitigated?

**Comment by jblankenhorn** [comment]
1) is handled in #229
