### ISSUE TITLE
Deutsch language instead of English  

### ISSUE THREAD

**Issue by redberre** [w11k/calendar-for-trello#204]
Wrong localization in SUN MON TUE... after the first open

**Comment by CanKattwinkel** [comment]
The localisation is now derived from your browsers locale. Please check if this issue is still valid and then re-open.

**Comment by jblankenhorn** [comment]
@CanKattwinkel shows english for me in chrome

**Comment by CanKattwinkel** [comment]
Yepp, the wording will always be English until we get angular i18n up and running. But the week start is now correctly read from the browsers locale and no longer a setting.
