### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by JEricaM** [w11k/calendar-for-trello#207]
Hi, I would like to change the default language from Deutsch to Italian, how can I do it? 
I don't understand where the default language has been set, if there is a file or something else to change...

Someone can help me?
Thank you

**Comment by gahawkey** [comment]
I also find that I set the language to English, but it keeps reverting, then clicking on the settings menu fixes it until it refreshes next time. It's like the setting isn't persistant.

Loving the app though! Thanks 👍

**Comment by CanKattwinkel** [comment]
The i18n issue hadn't received much attention for a long time. We'd need a bump to Angular 6 and then follow this guide:
https://angular.io/guide/i18n

The translation is done in xliff files, the default language is set during build. We can use Google Translate to autogenerate i18n for several languages.

**Comment by kaihenzler** [comment]
@JEricaM we enabled i18n but need help from the community to translate the application. We would really appreciate it if you could take over the italian part. In the Readme there is a link to an online translation tool where you could upload the src/locale/messages.it.xlf file and translate it there and download it afterwards and create a PR that only changes the messages.it.xlf file. Everything else has been taken care of

**Comment by JEricaM** [comment]
> @JEricaM we enabled i18n but need help from the community to translate the application. We would really appreciate it if you could take over the italian part. In the Readme there is a link to an online translation tool where you could upload the src/locale/messages.it.xlf file and translate it there and download it afterwards and create a PR that only changes the messages.it.xlf file. Everything else has been taken care of

I would be happy to help translate this amazing calendar. Asap I'll check the readme file!

**Comment by JEricaM** [comment]
I've translated the file but I'm not able to make a pull right now. But If can be usefull I can attach the translated file here!

**Comment by kaihenzler** [comment]
@JEricaM you can do that as well

**Comment by JEricaM** [comment]
[messages.it.zip](https://github.com/w11k/calendar-for-trello/files/2500741/messages.it.zip)

Here the zip with the italian translation file!!
