### ISSUE TITLE
Filter by labels instead of Members

### ISSUE THREAD

**Issue by JEricaM** [w11k/calendar-for-trello#209]
Hi, I have a question about the filtering process.

Premise: I have the same labels for all my boards.
 
There is a way, in calendar, to filter by labels, in the same way it filters by members?

I would also be available to implement this feature, but I would like to know if, with the actual code, it's possibile to do this or it's necessary to change the code drastically.

Thank you

**Comment by jblankenhorn** [comment]
@JEricaM i think it should be possible without bigger changes. all the data is already in Card.ts

**Comment by JEricaM** [comment]
thank you, I'll check the code better and I'll try to do it :)

**Comment by CanKattwinkel** [comment]
Is implemented, please review and re-open if anything doesn't work as intended.
