### ISSUE TITLE
Suggestion: Make "List:" and "Board:" in front of the list- and the board-name switchable

### ISSUE THREAD

**Issue by Ollisterhase** [w11k/calendar-for-trello#210]
Moin,
with the new there are "List:" and "Board" in front of the list- and board-names. Could you make it switchable?
We have just a 800x600 Screen for our Calendar-View and we need every pixel to show the list/boardnames. So the List: and Board: are useless for us.
Nevertheless your calender is wonderful!

**Comment by jblankenhorn** [comment]
i just removed the labes, they are not needed i think

**Comment by jblankenhorn** [comment]
Thx
