### ISSUE TITLE
Fix Paypal again

### ISSUE THREAD

**Issue by CanKattwinkel** [w11k/calendar-for-trello#223]
new button required

**Comment by jblankenhorn** [comment]
@CanKattwinkel why is it gone?

**Comment by CanKattwinkel** [comment]
@jblankenhorn It was originally only possible to integrate the PayPal button via a very hacky solution. This stopped to work due to some changes on the side of PayPal. 


I cant request a new button code, could you do it? 
https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/#

Or send me the login.
