### ISSUE TITLE
Hours not correctly displayed (all set to 12am)

### ISSUE THREAD

**Issue by crommie** [w11k/calendar-for-trello#224]
![afbeelding](https://user-images.githubusercontent.com/11227077/44330170-9f3d1500-a466-11e8-9cdf-e7f23f892ce7.png)

**Comment by CanKattwinkel** [comment]
@crommie thanks for the bug report, the issue will be fixed shortly!

**Comment by CanKattwinkel** [comment]
The issue was resolved in version 2.1.4 and deployed.
