### ISSUE TITLE
Wrong date/weekday combination

### ISSUE THREAD

**Issue by crommie** [w11k/calendar-for-trello#225]
Today is Tuesday August 21 :-)

![afbeelding](https://user-images.githubusercontent.com/11227077/44387738-9c095e00-a526-11e8-886e-695de9011650.png)

**Comment by CanKattwinkel** [comment]
@crommie thank you again for the bug report. The issue has been resolved and will be fixed with calendar version 2.1.5!

If you find any more errors, we will be happy to hear from you!

**Comment by crommie** [comment]
Don't worry, you will!
