### ISSUE TITLE
More than 2 Trello boards?

### ISSUE THREAD

**Issue by soluxima-erik** [w11k/calendar-for-trello#23]
Very awesome project. I would love to help beta test it.
In its current state it only grabs 2 boards. Is there a way to allow the calendar to grab all boards with calendar Power-up enabled?

**Comment by jblankenhorn** [comment]
Hello,

could you please try again, normally it should grab all of your boards!

Kind regards

**Comment by soluxima-erik** [comment]
Ensured I have more than 2 boards with active calendar ical feeds, removed all permissions (to force new 'grab'),refresh the web app, the 'grab' still only finds 2 boards.

The boards are all in a Business Trello Account Organization.

**Comment by CanKattwinkel** [comment]
hey erik - the calendar does not require activated calendar power ups in your board. it only relies on due date per card and should scrape all your boards. 
Could it be that you have no active cards in the current months except of the 2 boards displayed? If a board has no cards it will not be displayed in the filter.

cards will only be displayed if:
* card has due date
* you are assigned to that card

If you want to get access to all cards in your boards - without beeign assigned to them we could pbl add a feature - tell us if desired.
best regards
can

**Comment by soluxima-erik** [comment]
@CanKattwinkel you are right, I only have due cards assigned to me in 2 boards (which is handy in its own way). Maybe a toggle to switch "all cards" or "my cards" could be an interesting feature, esp once the coloring feature works.
Again, this project is awesome.

**Comment by CanKattwinkel** [comment]
added the observer mode in which you can access all cards of all members. It is a little bit slower since it creates one network request per board. coloring feature works again with refresh -> closed.
