### ISSUE TITLE
date error on September first

### ISSUE THREAD

**Issue by sylvainbilo** [w11k/calendar-for-trello#246]
Hello, there is a mistake on the calendar: September 1rst should be on Sunday, not Monday. On the August calendar, we can see the date rightly, that is on sunday (see attached files). October calendar seems to get it right.
![sept](https://user-images.githubusercontent.com/54562730/64492375-3ecf7000-d241-11e9-9f2d-049a0a651592.JPG)
![août](https://user-images.githubusercontent.com/54562730/64492383-498a0500-d241-11e9-9331-0e373636f62b.JPG)

**Comment by helenhibbins** [comment]
It's really confused me! It's annoying because my cards show as overdue the day before they are due!
