### ISSUE TITLE
Error message when dragging and dropping calendar events

### ISSUE THREAD

**Issue by Dreamfish19** [w11k/calendar-for-trello#25]
![error_message](https://cloud.githubusercontent.com/assets/9974678/8796410/e40b3af8-2f94-11e5-8af0-4689385b77ab.png)

Hi,
when dragging and dropping calendar cards on Safari 8.0.7 // OSX Yosemite, we receive the error "Oops, something went wrong". Reloading the page does not fix the issue.

**Comment by jblankenhorn** [comment]
Hi,

please use GoogleChrome as a Workaround. We will fix the issue asap!

Regards

**Comment by CanKattwinkel** [comment]
hello @Dreamfish19 fixed, please test on your system.
