### ISSUE TITLE
Dates/Day wrong for December

### ISSUE THREAD

**Issue by helenhibbins** [w11k/calendar-for-trello#250]
In the November Calendar view, December 1 is a Sunday - correct.
In the December Calandar view, December 1 is a Monday - incorrect.

**Comment by GitGilGml** [comment]
There was an error on September 2019 too... Doesn't seem to be a big issue... Does someone dealing with code can just look what's the problem ? In the meantime, the week view is always behaving alright !

**Comment by GitGilGml** [comment]
With all the respect for your work, what is the use of a calendar tool if the core is wrong ?
