### ISSUE TITLE
Leap Year Throws March Dates Out

### ISSUE THREAD

**Issue by MIchaelBWatson1** [w11k/calendar-for-trello#253]
The date of March 1st is shown on the wrong day in monthly view.  All subsequent days in March are a day out.
March 1st is on a Sunday, and that appears correctly at the end of the February monthly view, but moving forward one month, march 1st is shown on Monday, and the whole month is then a day out.
However, this error is corrected on the 1st of April when viewing April, so it is only the March monthly view that is in error.

When viewed weekly, the dates in March are all correct.

**Comment by GitGilGml** [comment]
This problem occured sometimes, within last year too.
Nobody seems to care about this.
I am quite sure it is not complicated for a good programmer to fix this.

**Comment by MIchaelBWatson1** [comment]
I have just noticed that the problem only occurs when weekends are displayed.  If they are hidden, it looks like the dates are correct.

**Comment by dini-mohd** [comment]
The latest update has fixed this issue.
