### ISSUE TITLE
Team member photos no longer showing

### ISSUE THREAD

**Issue by crommie** [w11k/calendar-for-trello#258]
![afbeelding](https://user-images.githubusercontent.com/11227077/82308571-421b1e00-99c2-11ea-88bb-bc2e18cf78a4.png)

**Comment by lolozere** [comment]
I have the same problem with Firefox on Ubuntu 18.04
Example : the link https://trello-avatars.s3.amazonaws.com/3278a6f8f02d873d89a7243ff169f3ba/50.png (used as src of the img tag) returns : 

NoSuchBucketThe specified bucket does not existtrello-avatars292949A21AD49DDFsjKnZVC1ymIp2FFkfvkgANun1bQjjbqScxlOGGNl3p053cKnjAyD6TvbH8ly314OcVDxT/Sp1R4=

**Comment by lolozere** [comment]
From Trello UI the right src should be : https://trello-members.s3.amazonaws.com/519d636cdf5fe9bd60001772/3278a6f8f02d873d89a7243ff169f3ba/50.png

**Comment by lolozere** [comment]
After searching in the source code if have found this : 

`
<div class="right" >
    <div class="memberPictures"  *ngIf="!card.dueComplete">
      <ng-container *ngFor="let id of card.idMembers">
        <img *ngIf="getAvatar(id)" src="https://trello-avatars.s3.amazonaws.com/{{getAvatar(id)}}/50.png">
      </ng-container>
    </div>
  </div>
`

in https://github.com/w11k/calendar-for-trello/blob/e5b215943e1428c51cb3e52c21b6eef44d6dc9d2/src/app/calendar/calendar-card/calendar-card.component.html

It seems that a another hash is missing : `519d636cdf5fe9bd60001772`

Do you know what it is ?

**Comment by crommie** [comment]
@w11k-schwenk or @w11kjanik anything you can do about this problem?

**Comment by jblankenhorn** [comment]
Thx for your input, i had a conversation with @dini-mohd yesterday that she is looking into the issue. It seems that the API from trello has changed ... 

we are working on it.

Thanks for using the calendar!

**Comment by jblankenhorn** [comment]
@dini-mohd i think the fix is described here https://stackoverflow.com/a/61640808/6594271

**Comment by dini-mohd** [comment]
#263 this issues is fixed. :)

**Comment by crommie** [comment]
Awesome :)
