### ISSUE TITLE
Cannot GET / + can't download binding.node from github

### ISSUE THREAD

**Issue by Hopsakee** [w11k/calendar-for-trello#280]
I tried to open my locally running Calendar for Trello today. But I got an 'Cannot GET /' message when I tried to open localhost:4200.

I then downloaded the latest version of Calendar for Trello and tried to 'npm install'.
I got several errors, starting with:

"Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node": HTTP error 404 Not Found
The link also doesn't work in my browser. I can find v5.

The next error is:
gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax

After that some errors which seems, to me, to be related.

I added the logfile.

Sincerely.
[2021-03-22T09_35_42_559Z-debug.log](https://github.com/w11k/calendar-for-trello/files/6181115/2021-03-22T09_35_42_559Z-debug.log)

**Comment by valentinschuele** [comment]
Hi @Hopsakee,

which version of nodeJS and npm you are using?

I have the following versions installed and it runs without any problems:

- npm: v6.9.0
- node.JS: v12.8.1


Try to install these versions and run following steps in the directory of your directory:

1. `npm install`
2. `npm run start`

If you still have problems feel free to contact us

Sincerely.
