### ISSUE TITLE
no sync with trello

### ISSUE THREAD

**Issue by gzara83** [w11k/calendar-for-trello#286]
it doesn't seem to sync with trello anymore

**Comment by Kalud-Z** [comment]
I just connected the App to my Trello account and the calender is synched perfectly.

If the bug still persists on your end, can you please explain the issue in a detailed manner ?
(you can use this [template](https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md) for bug reports)
