### ISSUE TITLE
Wrong Cards shown when opening the calendar

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/calendar-for-trello#42]
It seems like cards from local storage are displayed.

Correct Cards are shown after some seconds ...

**Comment by jblankenhorn** [comment]
@SimonWolf It seems, that cards aren't loaded at all, after first opening the page!

**Comment by SimonWolf** [comment]
The update from the Trello-server takes a few seconds. So the calendar shows the cards from localstorage first.

**Comment by jblankenhorn** [comment]
In my case, the local Storage seems to have a dataeset, which is > 1 day old.
Either
a) Store to local Storage more often (how often is it done??)
b) improve Trello-Loading, and show a Loading indicator while this is done ...
