### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by BGH9019** [w11k/calendar-for-trello#45]
Hiya,

Thanks for this calendar app, it's amazing, Its really helped with reorganizing in Trello. The interface is very attractive. The tick-list is overlapping the board names ATM,  is this something you're working on? or is this an issue with my browser? also, are you able to add a feature for filtering card labels/members. It would be fab if there was an action to deselect all, it takes a while to deselect when you only want to see details for one board. A Search facility in the filtering would be really awesome. Also, Day/Week view options would be really helpful.

Thanks

B

**Comment by jblankenhorn** [comment]
Hello,

in the upper right corner, there is a search symbol which allos you to search in all your cards.

Best
