### ISSUE TITLE
Issue running "grunt dev"

### ISSUE THREAD

**Issue by Shaunm44** [w11k/calendar-for-trello#46]
Hey,

I'm new to Grunt and only used node and npm briefly before, but I'm hitting a snag with running "grunt dev" in the terminal.

Got the following errors:

---
shaun$ grunt dev
Warning: Task "dev" not found. Use --force to continue.

Aborted due to warnings.

shaun$ grunt dist
Warning: Task "dist" not found. Use --force to continue.

Aborted due to warnings.

---

No idea what I'm doing wrong. Any help to get a local version up and running is greatly appreciated!

Also, I'm not to familiar with GitHub, so I hope I'm posting my request in the right area. :-)

**Comment by SimonWolf** [comment]
hi shaun,
if I understood correctly, this could be your problem:
You have to call "grunt dev" in the root directory of the project, where grunt can find the Gruntfile.js!
e.g.:
simon:~/projects/calendar-for-trello(master) $ grunt dev

**Comment by Shaunm44** [comment]
Thanks Simon!

I've been doing that, but it wasn't working. It's a series of issues where I fix one, but it creates another.

First, I'll describe my setup.
OSx El Capitan
NPM: 3.6.0
Bower 1.7.2

The "npm install" and "bower install" go through without error. A few warnings, but no errors. But I run "grunt dev" and I get a list of errors about the NPM module "fabs/node_modules/grunt-...". Here's the actual output:
`shmos-macbook:trelloCal shaun$ grunt dev
No developer config found!
>> Local Npm module "fabs/node_modules/grunt-contrib-clean" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-copy" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-htmlmin" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-compass" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-concat" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-cssmin" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-connect" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-compress" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-contrib-less" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-connect-proxy" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-karma" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-ng-annotate" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-minjson" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-replace" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-html2js" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-shell" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-bless" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-bump" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-conventional-changelog" not found. Is it installed?
>> Local Npm module "fabs/node_modules/grunt-protractor-runner" not found. Is it installed?
Warning: Task "shell:bower" not found. Use --force to continue.

Aborted due to warnings.`


After that, I figured NPM just didn't properly install the fabs subdependencies, so I do that manually with "npm install" inside the fabs module directory (node_modules/fabs/). Running NPM creates the following warnings about missing dependencies:
`npm WARN grunt-karma@0.10.1 requires a peer of karma@~0.12.0 but none was installed.
npm WARN karma-chrome-launcher@0.1.4 requires a peer of karma@>=0.9.3 but none was installed.
npm WARN karma-firefox-launcher@0.1.3 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-junit-reporter@0.2.2 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-phantomjs-launcher@0.1.4 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-ng-scenario@0.1.0 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-ie-launcher@0.1.5 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-jasmine@0.3.5 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-opera-launcher@0.1.0 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-safari-launcher@0.1.1 requires a peer of karma@>=0.9 but none was installed.
npm WARN fabs@0.10.0 No license field.`

To fix this unmet dependency, I update the project to get karma 0.12.0:
`sudo npm install --save-dev karma@0.12.0`

After that, the terminal isn't screaming at me any more about unmet dependencies. Now, I return to my project's root directory, run "grunt dev" because all dependencies should be there and
`shmos-macbook:trelloCal shaun$ grunt dev
No developer config found!
Warning: Task "dev" not found. Use --force to continue.

Aborted due to warnings.`

So after all that digging and playing in the code, still no avail. I know this is a boatload of info and a potentially complex problem, but I'm not too familiar with dependency managers and following the instructions to the 't' didn't work for me. Tried google searching, but didn't come up with anything. :-(

Any and all help on this is greatly appreciated!

**Comment by SimonWolf** [comment]
Hi @Shaunm44
I tried  to use a quite similar setup. And look there, i got the same problems using npm version 3.7.2! So try using an other version of npm/node! (now I'm using an older npm (v2.14.6))
You can manage your different npm versions for different projects with the useful [Node version Manager](https://github.com/creationix/nvm).
So delete your node-module and vendor folder in your project, install an other npm version. and delete your npm cache with `npm cache clean`! I hope this can fix your problems!

**Comment by SimonWolf** [comment]
@Shaunm44  I updated the fabs-version. Now, it should work with npm 3 too!

**Comment by Shaunm44** [comment]
Awesome! I'll give that a shot!

Thanks @SimonWolf!

**Comment by Shaunm44** [comment]
Bad news - no luck...

I grabbed the latest code from the master-branch, started it all from scratch and still nothing. Looks like that problem with the 'fabs' module is fixed (thanks!), but grunt is still failing. Here's the verbose response

`shmos-macbook:trelloCal shaun$ grunt dev -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
reading fabs configuration
used config folder: /Users/shaun/Sites/trelloCal/build-config
Reading ./package.json...OK
Parsing ./package.json...OK
Reading ./.bowerrc...OK
Parsing ./.bowerrc...OK
fabs configuration read
reading tasks configuration
Reading ./.bowerrc...OK
Parsing ./.bowerrc...OK
Reading ./.bowerrc...OK
Parsing ./.bowerrc...OK
Reading bower.json...OK
Parsing bower.json...OK
Reading ./package.json...OK
Parsing ./package.json...OK
Reading ./package.json...OK
Parsing ./package.json...OK
Reading ./.bowerrc...OK
Parsing ./.bowerrc...OK
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'process'
>>     at Function.Module._resolveFilename (module.js:338:15)
>>     at Function.Module._load (module.js:280:25)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/Users/shaun/Sites/trelloCal/node_modules/fabs/src/utils/node.js:2:15)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)

Running tasks: dev
Warning: Task "dev" not found. Use --force to continue.

Aborted due to warnings.`


I'm not familiar with grunt at all and tried googling fixes to no avail, so let me know if I'm doing anything wrong. If you have any ideas on how to fix this, then I'll give it one more shot. If not, I'll just build something from scratch.

**Comment by CanKattwinkel** [comment]
Closing this for now, please leave a note if still recent

**Comment by lhardie** [comment]
I'm trying to run "grunt dev" and having the same problem.  I get the following error:
`No developer config found!
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'process'
Warning: Task "dev" not found.`

**Comment by lhardie** [comment]
So I ran "npm install process" which removed the above error, and then I had to run "grunt dev" as a user that was not sudo, and then it worked.  Sorry to re-open this issue.
