### ISSUE TITLE
Show assigned user on card

### ISSUE THREAD

**Issue by neilcsmith-net** [w11k/calendar-for-trello#49]
Would it be possible to show the assigned users (names or avatars) on cards?  This would be particularly useful when looking at the view of all cards, although I guess useful to see other assignees even when only viewing your own cards.

Great application btw! :smile:

**Comment by CanKattwinkel** [comment]
Either by showing really small thumbnails or with a info modal per card on click (open in Trello via double click?)

**Comment by CanKattwinkel** [comment]
We've come to the conclusion that we don't want to substitute Trello's core features. Also the space for the cards is limited. Therefore we will not add this feature. But a link that directly takes you to the Trello card.
