### ISSUE TITLE
Not all cards with due dates display

### ISSUE THREAD

**Issue by BernardBrzezinski** [w11k/calendar-for-trello#51]
I am having a problem with cards not displaying in the calendar for a particular user. Some display, but most of them do not. All of the cards in question have the proper due dates and show up in the normal Trello calendar.  Any thoughts?

**Comment by BernardBrzezinski** [comment]
I figured this out.  The icon to show cards of all members was not apparent to me.  Thank you!

**Comment by CanKattwinkel** [comment]
I'll close this issue since you figured it our yourself. :)
