### ISSUE TITLE
Sync with Google Cal?

### ISSUE THREAD

**Issue by anniejw6** [w11k/calendar-for-trello#53]
Is there a way to grab a feed of this calendar and add it to Google Cal?

(PS This app is amazing!)

**Comment by CanKattwinkel** [comment]
Hello Annie, 
to do so, go to the wanted Trello board and enable the calendar in Trello itself (Menu on the right side, extras -> enable calendar power up). Then enable ical feed. 
![image](https://cloud.githubusercontent.com/assets/11500619/14597507/68e94a2e-054d-11e6-99ad-1cd1ad30f806.png)

Now you can add this calendar to google calendar. 

let me know if you experience any problems. :)

**Comment by anniejw6** [comment]
I know I can do that for each board, but is it possible to add *all* of the boards that I've selected using one calendar?

**Comment by CanKattwinkel** [comment]
I'll look into it. Might be possible to automate this process. Result would be a single ICS that merges all boards. Due my current workload this might take a while. 

Notes:

https://developers.trello.com/advanced-reference/board#put-1-boards-board-id-prefs-calendarfeedenabled
https://developers.trello.com/advanced-reference/board#post-1-boards-board-id-calendarkey-generate

**Comment by blizzmonkey** [comment]
Google cal is really slow to update Trello.  A good fix might be to import Google cal into this calendar.

**Comment by CanKattwinkel** [comment]
Currently a google export is out of scope. Therefore I'm going to close this issue for now.
