### ISSUE TITLE
After opening: Cards from cache do not reflect last changes

### ISSUE THREAD

**Issue by jblankenhorn** [w11k/calendar-for-trello#57]
How to reproduce
* Open the app
* change dates of cards in the app
* Reload

Cache does not reflect the last changes

**Comment by alexander-q** [comment]
I'm getting this problem particularly badly this week. Cards that have had the date removed via Trello, or that have been dragged to new dates, are not reflecting these changes in the calendar

**Comment by jblankenhorn** [comment]
Hello Alexander, 

thanks for the input. We are currently re-writing the calendar in TypeScript, and cleaning up while this process.
We hope this will be solved soon.

In the meantime, pleas use the refresh button in the top-right corner!

**Comment by CanKattwinkel** [comment]
fixed in 2.0.0-alpha.01
