### ISSUE TITLE
Option between week view and month view

### ISSUE THREAD

**Issue by JadeLaurenCawthray** [w11k/calendar-for-trello#58]

**Comment by jblankenhorn** [comment]
Hello @JadeLaurenCawthray ,

what do you exactly mean?

Kind regards

**Comment by JadeLaurenCawthray** [comment]
Currently you can only view the caldendar a whole month at a time. 
It would be great to be able to choose between view the calendar a week at a time and a month at a time.
Does that make sense?

**Comment by sergioiriarte** [comment]
I was actually looking if anyone had already proposed this option. Having a weekly view would be very helpful.

**Comment by CanKattwinkel** [comment]
This feature has landed in Trello Calendar v2 and will be published soon.
