### ISSUE TITLE
Request - ability to share calendar

### ISSUE THREAD

**Issue by JadeLaurenCawthray** [w11k/calendar-for-trello#60]

**Comment by jblankenhorn** [comment]
Hello @JadeLaurenCawthray ,

you mean as ical?

Kind regards
Jan

**Comment by JadeLaurenCawthray** [comment]
@jblankenhorn

I dont really understand how ical works.  But what I'd like to be able to do is invite my line manager to be able to see my calendar, so that they can see what my work commitments and deadlines are, more clearly. 

I have used ical to link my boards to google calendar and have then invited my line manager to see the boards that way.  But google calendar then seems like a middle man, when I could get my line manager to look directly at the trello calendar.

**Comment by CanKattwinkel** [comment]
@JadeLaurenCawthray assuming that your line manager has access to the boards, he could toggle the person mode to see all cards of all members. To perfectly fulfill your needs we probably should add a filter to view all cards of a single board member.

**Comment by JadeLaurenCawthray** [comment]
@CanKattwinkel  Ah, I see.  If I make him a member of my boards, then he could create a calendar of them himself?

**Comment by CanKattwinkel** [comment]
Yes. By default the calendar only shows your personal cards. If the  "show cards of all members" option is enabled, cards of all board members are loaded. 
 
![image](https://cloud.githubusercontent.com/assets/11500619/15704742/4175082c-27ec-11e6-9c03-941d34a2c3fc.png)
