### ISSUE TITLE
Request - create cards in the calendar

### ISSUE THREAD

**Issue by JadeLaurenCawthray** [w11k/calendar-for-trello#61]

**Comment by jblankenhorn** [comment]
Hello @JadeLaurenCawthray ,

we currently see this calendar only as an aggregation of trello boards. Meetings are a total different thing.
But i like the ability to create cards!

Kind regards
Jan

**Comment by JadeLaurenCawthray** [comment]
@jblankenhorn  Thanks for the response.  Yeah ability to make cards from the calendar would be really useful. 

Jade

**Comment by CanKattwinkel** [comment]
Required Fields:
- Card Title
- Card Due
- Card Description
- Board
- Members (fetch members of board before)
