### ISSUE TITLE
Trello calendar identify owner of the card

### ISSUE THREAD

**Issue by cconstante78** [w11k/calendar-for-trello#65]
There should be a way to know who the responsible person in the card is.

**Comment by CanKattwinkel** [comment]
I'm skeptical. There are many users with large numbers of cards. It may be annoying to leave the calendar but it helps us to keep the cards small. 

Are more people interested in such a feature? We could add a "CardPreview" feature that allows you to see some Information of the card. For example when you press the ALT key and move the Mouse over the card. 

Waiting for more feedback.
