### ISSUE TITLE
Ability to rearrange order of cards within a day.

### ISSUE THREAD

**Issue by JadeLaurenCawthray** [w11k/calendar-for-trello#68]
Would be great to be able change the timings of the cards, by simply rearranging the cards within a day.

**Comment by CanKattwinkel** [comment]
This is something that I can imagine for the next major update of the calendar since it requires some changes in the structure and split days up into hours. 

Sooner or later this feature will be implemented, but expect some delay.

**Comment by JadeLaurenCawthray** [comment]
Great to hear this is on the to do list.

Just to say I am finding the calendar so great at helping me manage my work load.  So thank you so much for all the work you have done so far on this,

Jade

Jade Lauren Cawthray,
Science Community Coordinator (SYNTHESYS)

Natural History Museum,
Cromwell Road,
London,
SW7 5BD

Tel:  +44 (0)20 7942 6279

**Comment by CanKattwinkel** [comment]
@JadeLaurenCawthray 
Great to her that you like it!  

fyi: I just edited your comment since it contained your full mail signature with personal information. It is now removed. :)

**Comment by JadeLaurenCawthray** [comment]
Woops. 

Thank you. :)

**Comment by alexander-q** [comment]
I'd love this too. I use the calendar as a to-do list. I currently manage priority by changing the time on the card (they are sorted by time, then alphabetically). I'd suggest a sorting mode: time/manual option and then allow drag to rearrange. 

Keep up the good work!

**Comment by CanKattwinkel** [comment]
This feature has just landed in our new version of the calendar. I will close this issue for now.  

But Trello Calendar V2 is not yet finished - this means the feature is not available yet.
