### ISSUE TITLE
Differences on Different Computers

### ISSUE THREAD

**Issue by rhkaufer** [w11k/calendar-for-trello#69]
I just joined and on my Macbook, all of my cards show up correctly.  On my iMac, not all cards show up, I have refreshed, I have selected and deselected boards and played with all of the settings.

**Comment by CanKattwinkel** [comment]
Currently the calendar has so many users that we are reaching the API limit. We are already working on this issue. 

Could you submit a screenshot of your browsers console? (F12 in Chrome and Firefox, Safari ⌥⌘C ) Just to make sure that your issue is not connected to the mentioned above. You can either share it public via github or send an email to me ( kattwinkel@w11k.de ).

**Comment by rhkaufer** [comment]
I am sorry about this basic question but what do you mean by "browsers
console" I am using Chrome on a Mac.

Thanks

**Comment by CanKattwinkel** [comment]
Dont worry, I'll guide you trough:

1. First go to the Trello Calendar
2. Now press the following Keys on your Keyboard: `Cmd + Opt + J`
3. The JavaScript Console will pop up
4. If you see any errors (red)  there like in my example then please send me the screenshot

![image](https://cloud.githubusercontent.com/assets/11500619/18015310/654a7f4c-6bc7-11e6-8d11-54954386e33a.png)

**Comment by rhkaufer** [comment]
Thanks, the first three items were there like yours, but there were no
error messages in red

**Comment by CanKattwinkel** [comment]
So you are not affected from this issue. Have you already manually refreshed the calendar? Also make sure to have all desired boards enabled and to chose the correct mode. The calendar has a personal mode where you will only see the cards where you are assigned plus the observer mode where you can see all cards of all board members with due date.  All these options are located in the upper right corner as you can see in the screenshot:

![image](https://cloud.githubusercontent.com/assets/11500619/18078376/72dce3b8-6e8b-11e6-85d0-5a0731b22817.png)

If you still experience issues please make sure to delete your cache and try again. I hope this helps!
