### ISSUE TITLE
Can't sync multiple calendars

### ISSUE THREAD

**Issue by graphicchar** [w11k/calendar-for-trello#70]
The boards are clicked in the menu, but none are showing up on the "calendar-for-trello" How can I make all the boards visible together? Right now none are showing on the site. Within Trello, I can see different calendars but not together. I have enabled the calendar powerup and the GitHub powerup.

Thank you for your help!

**Comment by CanKattwinkel** [comment]
The boards should be displayed if there are cards in the displayed month. These cards need to have a due date and you need to be assigned to the card as a member. Also the board must not be disabled in the deselect-board menu on the upper right corner of the calendar. 

Also make sure to refresh manually with the refresh button inside the calendar. If you want to load all cards regardless of the member you have to enable the slower observer mode by clicking on the person which is also on the upper right corner. 

![image](https://cloud.githubusercontent.com/assets/11500619/18078193/8f6ff94e-6e8a-11e6-94e9-5acf704af401.png)


There is no need to enable the calendar power up. If you still experience issues please make sure to delete your cache and try again. I hope this helps!
