### ISSUE TITLE
No data populating in the hosted app

### ISSUE THREAD

**Issue by iPenguin67** [w11k/calendar-for-trello#71]
I just registered an account on calendar-for-trello.com and connected it with my Trello boards. The web app sees my boards (the names and toggles are visible), but it does not populate the calendar with any of the cards with due dates. 

I did enable iCal feed on the boards. I can't find any additional settings on the web app that would lead me to believe I need to do anything extra to "see" those cards.

**Comment by jblankenhorn** [comment]
Hello @iPenguin67 , 

* You cannot register an account in the calendar, you can only login with your trello account. Maybe this is the problem?
* stupid question: Do your cards have duedates?
* Did you "enable" your boards in the "board settings"?
* You do not need to set anything in Trello ...

**Comment by CanKattwinkel** [comment]
And make sure to join the cards as a member or to enable the observer mode (default is personal).
In personal mode you'll only see your cards. Also make sure to refresh the calendar (not the browser window) by pressing the reload button in the upper right corner.
 
![image](https://cloud.githubusercontent.com/assets/11500619/18078431/c0d048b2-6e8b-11e6-82ac-01d11266300b.png)

**Comment by iPenguin67** [comment]
I might have misspoken - when I joined, I did so by entering my Trello account info. I can see all the boards associated with my Trello account in board settings. The cards just aren't populating. The cards have due dates and 3 of the boards have the calendar enabled (as well as the iCal feed enabled). 

I'm not sure how to "join the cards as a member or to enable the observer mode" though -- I didn't see that option, but I'll keep digging around.

**Comment by CanKattwinkel** [comment]
@iPenguin67 the option is in the upper right corner - the person icon. The tool tip says "show cards of all members". 

icon shows one person -> personal mode,
icon shows group of persons -> observer / team mode

**Comment by iPenguin67** [comment]
Got it, looks like it's working now. The tool tips don't show up for me for some reason, and I had to click it, unsubscribe from a board, resubscribe, and then click it again for it to work.

**Comment by CanKattwinkel** [comment]
I'm sorry for the trouble you experienced, this will be improved in the next version!
