### ISSUE TITLE
Drag to Complete

### ISSUE THREAD

**Issue by alexander-q** [w11k/calendar-for-trello#73]
Feature Request: **The ability to be able to drag the card into a trash bin to archive it, or press an archive icon on the card (or ideally, perform some custom action on it like "move to right-most list and remove due-date").**

I use the calendar to organise my casework each week. I have one board per client, and at the end of each day I drag around the cards to a suitable spot when I can complete the assigned task.

When I complete a task, my current workflow is to click the card to open it in trello, remove the date, then move it to my "Done" list. I have a lot of tasks so it takes a lot of time to do this process on each one as it is completed.

**Comment by jblankenhorn** [comment]
Good Idea. We will put it on our list!

**Comment by CanKattwinkel** [comment]
Implemented a function to either remove due date or send a card to archive. 

It would be possible to add another custom drop zone with predefined actions but this is out of scope for version 2.0.0.

**Version 2.0.0 Preview:**
https://w11k.github.io/calendar-for-trello/
