### ISSUE TITLE
Week and day view

### ISSUE THREAD

**Issue by SMukta** [w11k/calendar-for-trello#76]
First- thumbs up for the app! wonderful!
I would like to request you to add week and day views. It will help the workflow greatly.
Thank you!

**Comment by CanKattwinkel** [comment]
Hello thanks for the feedback!

This is actually a duplicate of https://github.com/w11k/calendar-for-trello/issues/58

I'll close this issue. The feature will definitively be implemented soon.

**Comment by SMukta** [comment]
Wonderful. Thank you!
