### ISSUE TITLE
i18n: Anuglar 2 localization

### ISSUE THREAD

**Issue by CanKattwinkel** [w11k/calendar-for-trello#84]
Implement localization with Angular 2

**Comment by CanKattwinkel** [comment]
waiting for ng2 cli..

see https://github.com/angular/angular-cli/issues/2201

**Comment by CanKattwinkel** [comment]
Give it a try: http://rolandoldengarm.com/index.php/2016/10/17/angular-2-automated-i18n-workflow-using-gulp/

**Comment by CanKattwinkel** [comment]
Feature has handled in angular cli, therefor i18n is not blocked anymore
 https://github.com/angular/angular-cli/pull/3098

**Comment by jblankenhorn** [comment]
see #207
