### ISSUE TITLE
Archive and delete task directly from Calendar

### ISSUE THREAD

**Issue by SMukta** [w11k/calendar-for-trello#87]
This feature can be very helpful.
Thank you again for your amazing job!

**Comment by CanKattwinkel** [comment]
Hello @SMukta,

the requested features "drag to complete" and "drag to remove due" just landed in our new version of the calendar. Right now it is in alpha and the current state is a functional preview. The current design is not yet implemented and there may be bugs.

But feel free to cast a glance:
https://w11k.github.io/calendar-for-trello/

You can track the current state here: 
https://github.com/w11k/calendar-for-trello/milestones

I'll close this issue, see https://github.com/w11k/calendar-for-trello/issues/73 for more information.

**Comment by SMukta** [comment]
Oh wow! Cannot wait for the release of this version. You guys are awesome!
