### ISSUE TITLE
No cards shown on calendar after sign-up

### ISSUE THREAD

**Issue by DonDino2** [w11k/calendar-for-trello#93]
Hello all,

Thank you so much for this application!

I signed up, and no cards are showing on the calendar... I've noticed a couple of older reports of the same issue, but they've been closed. I have manually refreshed, nothing's happened - been signed in for about half an hour now.

What can I do to get it to sync?

Thanks in advance!

**Comment by CanKattwinkel** [comment]
By default only card with **due date** + **assigned to you** will shop up. 

If you want to see cards of other members or cards with no members but a due date you need to activate the observer mode "show cards of all members". It is in the upper right corner of the calendar. 


does this solve your issue?


![image](https://cloud.githubusercontent.com/assets/11500619/20427122/b7066e3e-ad82-11e6-8ea3-0ca8d0805670.png)

**Comment by DonDino2** [comment]
Yes! Thank you! My cards were not assigned to me (or anyone else, it's just a personal board), so this fixed it. Thank you for the swift reply!
