### ISSUE TITLE
Mark as Done Feature

### ISSUE THREAD

**Issue by alexander-q** [w11k/calendar-for-trello#94]
Trello just added a mark as done feature, wherein a card can retain its due date but otherwise be marked as complete. In the internal Trello calendar this gives it a strikethough. Could you guys consider similar functionality? (with perhaps the option to hide it from your calendar completely when marked complete?)

**Comment by CanKattwinkel** [comment]
Hello @alexander-q,
currently we are developing v2 of calendar-for-trello. I'll put this on our features list!

**Comment by alexander-q** [comment]
I've been thinking about this feature (use your service on a daily basis at work) and I think the best solution would be to be able to tick a card done directly from the calendar. This would mean that for simple tasks, I could tick them off without ever needing to open Trello proper. When I do eventually open Trello proper, I'll see that the tasks are marked as done and can perform "cleanup" by moving them to a done list

**Comment by CanKattwinkel** [comment]
Note: This affects the "there are overdue cards" feature too.
