### ISSUE TITLE
"To many requests to Trello API"

### ISSUE THREAD

**Issue by alexander-q** [w11k/calendar-for-trello#97]
Hi guys. I've come back to work today after the Christmas break, and I'm getting frequent/multiple popups at bottom right that read "to many requests to Trello API". Will this impair functionality? What can I do about it? (Also, how's v2 coming along?)

**Comment by CanKattwinkel** [comment]
It might be that some data is not properly fetched and falsely displayed. That should be it. As mentioned in https://github.com/w11k/calendar-for-trello/issues/96 we've spent some effort to evade hitting the API limit until the next version is ready. (which ships with a completely different loading mechanism)

We are currently dependent from the release of material 2. I'd say, "some weeks". First usable alpha will be available soon.
