### ISSUE TITLE
problem installing for production - app not injected?

### ISSUE THREAD

**Issue by studioy** [w11k/calendar-for-trello#98]
I know this is going to be something silly on my part, but I just can't seem to solve this.

I installed the calendar successfully in development.  It ran beautifully at localhost.com:9000

However, now that I have run "grunt dist" and set up an actual site for it to run on, all I see at the website is the following:

`<% styles.forEach( function ( file ) { %> <% }); %>
<% scripts.forEach( function ( file ) { %> <% }); %>`

I'm not exactly sure what I've done wrong.

When I look at the requests, there are some bad requests that look like the following in the developer's console in Chrome:

`Request URL:http://trellocal.com/%3C%=%20file%20%%3E
Request Method:GET
Status Code:400 Bad Request`

Any help is appreciated.

**Comment by CanKattwinkel** [comment]
Hello,

to verify the required steps please install the npm module `http-server`. It is a lightweight server that will serve the application while we test your setup.

1. `npm install http-server -g`
2. change to project folder `cd calendar-for-trello` 
3. run the actual dist task `grunt dist`
4. start server  `http-server build-output/compiled/`
5. verify that visiting `localhost:8080` with your browser does serve the calendar 

If this works everything is fine. It seems to me, like you have opened the `src/index.html` file. You need to move the `build-output/compiled` folder to your server in order to serve the compiled application. The `src/index.html` holds only the raw source.

Hope this resolves your issue, let me know!

**Comment by studioy** [comment]
This works.  It appears I am setting the webroot incorrectly.

After running "grunt dist", should I set my webroot to be the directory at 'build-output/compiled' or should I copy the resulting files somewhere?

**Comment by CanKattwinkel** [comment]
Where do you want to host the calendar? 

If you use the output of `build-output/compiled` it should work on any http server. Like Apache or nginx webserver. 

Just move the files from `build-output/compiled/` to `htdocs/` (for Apache HTTP Server).

**Comment by studioy** [comment]
Thank you very much for your help.  I haven't run a built with grunt before and did not realize what the output of "grunt dist" would be.

I moved the compiled files to my public_html and all is working beautifully.

**Comment by studioy** [comment]
sorry, I spoke too fast.  Now I am having a token error.  Perhaps I have set up my folder structure incorrectly?

When I go to my app it asks me to authorize the calendar, and when I click the button to do so, it is trying to return me to this url:
/app/token?do=settoken&callback_method=fragment

which is throwing a 404 not found.

**Comment by CanKattwinkel** [comment]
Ah, I should add this information to the readme file... 

The calendar works with Angular UI Router in HTML5 mode. Therefore a redirect to the index.html is required. I dont know how familiar you are with single page applications.. thats a generall disadvantage. 

What web server are you using? You need a redirect that catches all folder like requests and forwards them to the index.html. It is acutally pretty easy:

https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode

**Comment by lhardie** [comment]
can it be done in an .htaccess file? I'm on apache.

**Comment by CanKattwinkel** [comment]
Yes it can: https://gist.github.com/jbutko/6b500210b4c6811bca54

**Comment by studioy** [comment]
@CanKattwinkel Thank you for all of your help today! I've got the calendar working now.
